### ISSUE TITLE
프로젝트 소개 좀 써 주세요 

### ISSUE THREAD

**Issue by mozodev** [codeforseoul/cigs#1]
난 사실 대강 들어서 아는데요...
README 파일에 다가 시간날 때 프로젝트에 대해 간단하게 설명해주세요.

https://gist.github.com/zenorocha/4526327
뭐 꼭 이렇게 할 필요는 없는데 리드미 파일 템플릿도 검색해보면 많이 나와요. 
구글 github readme template? 아님 평소 좋아하는 
오픈 소스 프로젝트들이 소개하는 내용들 참고하셔도 되고요. 
소개에 간단한 아이디어만 적고 프로젝트 진행하면서 추가하시면 되죠.
그러다가 내용이 너무 많아지만 위키에 페이지 만들어서 옮기고... ㅎㅎ

**Comment by anthonycorbacho** [comment]
How about this: https://gist.github.com/9195cb87b00862209ea2 ?

**Comment by thechunsik** [comment]
오 좋네요! 저도 다음에 이거 가져다 써야겠어요!

**Comment by kkh975** [comment]
간략하게 정리하면, 정부 사이트를 평가하는 사이트입니다. caniuse 사이트를 벤치마킹할까 하고 있습니다. 
다만 아직 readme 파일을 못만들고 있는 이유는 아직 어떻게 구체화 시켜야 할 지 고민하고 있기 때문입니다.
좀 더 명확한 그림이 그려지면 readme 작성해서 올리도록 하겠습니다.

**Comment by kkh975** [comment]
https://github.com/mozodev

**Comment by mozodev** [comment]
아 너무 어마어마하게 생각하지 마시고 방금 쓰신거 정도 올려놓으셔도 되요.. 다른 분들이 지나다니다가 보고 물어볼 수도 있잖아요 ㅎㅎ 그리고 약간 caniuse 처럼 몇 가지 기준 항목이랄까 그런거 예를 들어주면 더 이해가 잘 될 듯... 우리의 자랑스러운 액티브엑스를 포함해서 말이죠 ㅋㅋㅋ
